services:
  - type: web
    name: multilang-app  # Remplacez par le nom de votre choix
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn multilang_site.wsgi:application --bind 0.0.0.0:8000"
